name: deploy

on:
  release:
    types: [ published, edited ]
  push: 
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get

      - name: Build Web Project
        run:  flutter build web

      - name: Deploy web To GH-Page
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build/web/
